name: Melodle
services:
  backend:
    image: ${REGISTRY_URL}/${NOMBRE_GRUPO}/${NOMBRE_PROYECTO}/backend
    container_name: backend
    build:
      context: ./backend
    command: sh init.sh
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${DB_DATABASE}
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=${DB_HOST}
      - NODE_ENV=${NODE_ENV}
      - FRONT_URL=${FRONT_URL}
      - MUSIXMATCH_KEY=${MUSIXMATCH_KEY}
    depends_on:
      - database
  frontend:
    image: ${REGISTRY_URL}/${NOMBRE_GRUPO}/${NOMBRE_PROYECTO}/frontend
    container_name: frontend
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend/:/frontend
    build:
      context: ./frontend
      target: development
    depends_on:
      - backend
  database:
    image: ${REGISTRY_URL}/${NOMBRE_GRUPO}/${NOMBRE_PROYECTO}/database
    container_name: database
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/myconf.template:/etc/nginx/conf.d/default.conf
      - ./proxy/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
