name: Melodle
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/backend
    environment:
      - PG_DATABASE=${PGDATABASE}
      - PG_USER=${PGUSER}
      - PG_PASSWORD=${PGPASSWORD}
      - PG_HOST=${PGHOST}
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/:/usr/share/nginx/html
  database:
    image: database
    container_name: database
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/myconf.template:/etc/nginx/conf.d/default.conf
      - ./proxy/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  db_data: