name: caso2
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${DB_DATABASE}
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=${DB_HOST}
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/:/usr/share/nginx/html
  database:
    image: database
    container_name: database
    build:
      context: ./database
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5434:5432
  proxy:
    image: proxy
    container_name: proxy
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
