openapi: 3.0.0
info:
  title: Musixmatch API
  description: API para obtener letras de canciones usando Musixmatch
  version: "1.0.0"
servers:
  - url: https://api.musixmatch.com/ws/1.1
paths:
  /matcher.lyrics.get:
    get:
      summary: Obtener letras de una canción
      parameters:
        - name: q_track
          in: query
          description: Nombre de la canción
          required: true
          schema:
            type: string
        - name: q_artist
          in: query
          description: Nombre del artista
          required: false
          schema:
            type: string
        - name: apikey
          in: query
          description: Clave API
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      body:
                        type: object
                        properties:
                          lyrics:
                            type: object
                            properties:
                              lyrics_body:
                                type: string
        '404':
          description: No se encontraron letras